### ISSUE TITLE
COERCE isConnected defaults

### ISSUE THREAD

**Issue by firolightfog** [imDanSable/SIM#2]
Hi,

Would you please consider have a default scale for COERCE? 

Currently if there is no cable provided for "Quantize 1 input" then the output is just a bunch of 0Vs. I'd like to propose to have the chromatic scale (12 notes like C, C#, D, D#, E ...) as default if no cable is connected there. 

<img width="229" alt="image" src="https://github.com/imDanSable/SIM/assets/34127628/e11efd1d-40e1-4a6e-9004-fc297a17c7f3">

Regards, Andras

**Comment by imDanSable** [comment]
Yes.

**Comment by imDanSable** [comment]
Thank you for reporting. It was an overseen bug. Don't you think it would be more fitting to not quantize at all when there is no connection and let the original signal through without modification?
